Run_Something:
  desc: Showcase single command with multiple dependencies
  cmds: date
  deps: [No_Deps, Run_Something_Else]

No_Deps:
  desc: Single command with no dependencies
  cmds: ps

Run_Something_Else:
  desc: Showcase multiple commands
  cmds:
    - ls -lah
    - ls

third_task:
  desc: Showcase single command with single dependency
  cmds: ls
  deps: Run_Something
